---
settings:
  name: NetApp SMI-S Provider
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es
sidebar:
  entries:
  - title: Documentation NetApp SMI-S Provider
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/releasenotes.html"
  - title: Présentation du fournisseur NetApp SMI-S
    entries:
    - title: Présentation
      url: "/concept-overview.html"
    - title: Nouveautés de cette version
      url: "/reference-new-in-this-release-smis.html"
    - title: Utilisation du fournisseur NetApp SMI-S Provider
      url: "/reference-uses-of-data-ontap-smi-s-agent.html"
    - title: Performances et dimensionnement du fournisseur NetApp SMI-S
      url: "/reference-smi-s-agent-sizing-and-performance-information.html"
    - title: Composants du fournisseur NetApp SMI-S Provider
      url: "/reference-data-ontap-smi-s-agent-components.html"
    - title: Protocoles du fournisseur NetApp SMI-S Provider
      url: "/reference-data-ontap-smi-s-agent-protocols.html"
    - title: Interaction du fournisseur SMI-S de NetApp avec un hôte
      url: "/concept-how-smi-s-provider-interacts-with-a-host.html"
    - title: Profils SMI-S.
      url: "/concept-smi-s-profiles.html"
  - title: Flux de travail de déploiement
    url: "/concept-deployment-workflow.html"
  - title: Préparation du déploiement
    entries:
    - title: Présentation
      url: "/concept-prepare-for-deployment-overview.html"
    - title: Versions de systèmes d'exploitation prises en charge
      url: "/reference-supported-operating-systems.html"
    - title: Configuration matérielle requise
      url: "/reference-hardware-requirements.html"
    - title: Licences requises
      url: "/reference-required-licenses.html"
    - title: Plateformes de cluster prises en charge
      url: "/reference-supported-platforms.html"
    - title: Téléchargez le pack logiciel NetApp SMI-S Provider
      url: "/task-download-smi-s-provider.html"
  - title: Installez NetApp SMI-S Provider
    entries:
    - title: Installez le fournisseur NetApp SMI-S sur un hôte Windows
      url: "/task-install-smi-s-agent-on-a-windows-host.html"
  - title: Désinstallez NetApp SMI-S Provider
    entries:
    - title: Désinstallez NetApp SMI-S Provider depuis un hôte Windows
      url: "/task-uninstall-smi-s-agent-from-a-windows-host.html"
  - title: Validation de la préconfiguration
    entries:
    - title: Présentation
      url: "/concept-preconfiguration-task-overview.html"
    - title: Vérifiez l'état du serveur CIM
      url: "/task-verify-the-cim-server-status.html"
    - title: Ajouter un utilisateur de serveur CIM
      url: "/task-add-cim-server-users.html"
    - title: Vérifiez que le système de stockage fonctionne correctement
      url: "/task-verify-that-the-storage-system-is-working-correctly.html"
    - title: Générez un certificat auto-signé pour le serveur CIM
      url: "/task-generate-a-self-signed-certificate-for-the-cim-server-windows.html"
  - title: Gérer le serveur CIM
    url: "/task-manage-the-cim-server.html"
  - title: Gérer des systèmes de stockage
    url: "/task-manage-storage-systems.html"
  - title: Gérer les utilisateurs du serveur CIM
    entries:
    - title: Présentation
      url: "/task-manage-cim-server-users-overview.html"
    - title: Types d'utilisateurs CIM et opérations associées
      url: "/reference-types-of-cim-users-and-associated-operations.html"
  - title: Gérer les paramètres de configuration CIMOM
    url: "/task-manage-cimom-configuration-settings.html"
  - title: Gestion de la journalisation et du suivi
    entries:
    - title: Présentation
      url: "/concept-manage-logging-and-tracing-overview.html"
    - title: Configurer les paramètres du journal
      url: "/task-configure-log-settings.html"
      entries:
      - title: Niveaux de journalisation
        url: "/reference-logging-levels.html"
    - title: Gérer le tracé
      url: "/concept-manage-tracing.html"
      entries:
      - title: Spécifiez les paramètres de trace
        url: "/task-specify-trace-settings.html"
        entries:
        - title: Valeurs des paramètres de trace
          url: "/reference-trace-setting-values.html"
      - title: Spécifiez la taille du fichier de trace
        url: "/task-specify-trace-file-size.html"
      - title: Spécifiez le nombre de fichiers de trace enregistrés
        url: "/task-specify-the-number-of-trace-files-saved.html"
    - title: Active ou désactive le journal d'audit des commandes SMI-S.
      url: "/task-enable-or-disable-audit-log-for-smi-s-commands.html"
  - title: Gérer les paramètres avancés du SMI-S Provider
    entries:
    - title: Présentation
      url: "/concept-manage-smi-s-agent-advanced-settings-overview.html"
    - title: Spécifiez l'intervalle d'actualisation automatique du cache du SMI-S
        Provider
      url: "/task-specify-the-smi-s-agent-cache-refresh-interval.html"
    - title: Spécifiez la valeur de durée de vie du travail concret
      url: "/task-specify-the-concrete-job-lifetime-value.html"
    - title: Spécifiez la valeur du délai d'expiration ONTAPI
      url: "/task-specify-the-ontapi-timeout-value.html"
    - title: Spécifiez le nombre maximal de threads par file d'attente de service
        de messages
      url: "/task-specify-the-maximum-number-of-threads-per-message-service-queue.html"
    - title: Activez ou désactivez l'authentification pour le fournisseur NetApp SMI-S
      url: "/task-enable-or-disable-authentication-for-smi-s-provider.html"
    - title: Activer les indications dans SMI-S Provider
      url: "/task-enable-indications-in-smi-s-agent.html"
  - title: Gérer SLP
    entries:
    - title: Présentation
      url: "/concept-manage-slp-overview.html"
    - title: Spécifiez les options de configuration SLP
      url: "/concept-specify-slp-configuration-options.html"
      entries:
      - title: gestion des fichiers slp.conf
        url: "/reference-editing-the-slp-conf-file.html"
  - title: Commandes CIMOM
    entries:
    - title: cimconfig
      url: "/reference-cimconfig-command-options.html"
  - title: Commandes utilisateur CIM
    entries:
    - title: cimuser
      url: "/reference-cimuser-command-options.html"
  - title: Commandes SMI-S Provider
    entries:
    - title: Présentation
      url: "/concept-smi-s-provider-commands-overview.html"
    - title: ajout smis
      url: "/reference-smis-add.html"
    - title: smis adsécurisée
      url: "/reference-smis-addsecure.html"
    - title: smis cimom
      url: "/reference-smis-cimom.html"
    - title: cimserver smis
      url: "/reference-smis-cimserver.html"
    - title: classe smis
      url: "/reference-smis-class.html"
    - title: affichage de configuration smis
      url: "/reference-smis-config-show.html"
    - title: smis crp
      url: "/reference-smis-crp.html"
    - title: crsp smis
      url: "/reference-smis-crsp.html"
    - title: suppression smis
      url: "/reference-smis-delete.html"
    - title: disques smis
      url: "/reference-smis-disks.html"
    - title: exportations smis
      url: "/reference-smis-exports.html"
    - title: initiateurs smis
      url: "/reference-smis-initiators.html"
    - title: licence smis
      url: "/reference-smis-licensed.html"
    - title: liste smis
      url: "/reference-smis-list.html"
    - title: lun smis
      url: "/reference-smis-luns.html"
    - title: espaces de noms smis
      url: "/reference-smis-namespaces.html"
    - title: pools smis
      url: "/reference-smis-pools.html"
    - title: actualisation smis
      url: "/reference-smis-refresh.html"
    - title: slpd smis
      url: "/reference-smis-slpd.html"
    - title: version smis
      url: "/reference-smis-version.html"
    - title: volumes smis
      url: "/reference-smis-volumes.html"
  - title: Commandes SLP
    entries:
    - title: outil à outils
      url: "/reference-slptool-command-options.html"
    - title: slptool findattrs
      url: "/reference-slptool-findattrs.html"
    - title: slptool findsrvs
      url: "/reference-slptool-findsrvs.html"
  - title: Dépanner SMI-S Provider
    entries:
    - title: Présentation
      url: "/concept-troubleshoot-smi-s-agent-overview.html"
    - title: Erreur de refus d'accès
      url: "/reference-access-is-denied-error.html"
    - title: Erreurs possibles lors du chargement des bibliothèques partagées
      url: "/reference-possible-errors-when-loading-shared-libraries.html"
    - title: Connexion refusée
      url: "/reference-connection-refused-error.html"
    - title: 'Retour de fichier : aucun élément ONTAP en réponse'
      url: "/reference-no-ontap-element-in-response-error.html"
    - title: Les opérations de clonage/snapshot ne sont pas autorisées
      url: "/reference-clone-snapshot-operations-are-not-allowed.html"
    - title: Avertissement 26130
      url: "/reference-warning-26130.html"
    - title: 'HostAgentAccessDenied (ID : 26263)'
      url: "/reference-hostagentaccessdenied-error-id-26263.html"
    - title: Impossible de se connecter à localhost:5988
      url: "/reference-cannot-connect-to-localhost-5988-error.html"
    - title: Impossible de se connecter à localhost:5989
      url: "/reference-cannot-connect-to-localhost-5989-error.html"
    - title: SMI-S Provider tombe en panne sous Windows
      url: "/reference-handling-smi-s-agent-crashes-in-windows.html"
    - title: Problème de saisie des mots de passe contenant des caractères spéciaux
      url: "/reference-entering-passwords-containing-special-characters.html"
    - title: Technologie de clonage utilisée dans SMI-S Provider
      url: "/concept-clone-technology-used-in-smi-s-agent-4-0.html"
    - title: Confirmer la visibilité des objets importants
      url: "/concept-confirm-visibility-of-important-objects.html"
    - title: Condition requise pour l'utilisation de partages de fichiers sur Windows
      url: "/concept-requirement-for-using-fileshares-in-windows.html"
    - title: Les ports doivent être ajoutés manuellement en tant qu'exceptions sur
        les pare-feu non par défaut
      url: "/reference-non-default-firewalls-must-have-ports-manually-added-as-exceptions.html"
    - title: Impossible d'ajouter un système de stockage à l'aide d'un port HTTP ou
        HTTPS non par défaut
      url: "/reference-cannot-add-a-storage-system-using-a-nondefault-http-or-https-port.html"
    - title: Aucune réponse du serveur
      url: "/reference-no-response-from-the-server.html"
    - title: Problèmes de bibliothèque d'exécution
      url: "/reference-runtime-library-issues.html"
    - title: Le fournisseur SMI-S de NetApp prend beaucoup de temps à démarrer
      url: "/reference-smi-s-agent-takes-a-long-time-to-start.html"
    - title: Espace total géré pour un pool de stockage (volume) non-concorder
      url: "/reference-total-managed-space-for-a-storage-pool-aggregate-discrepancy.html"
    - title: Chemin réseau introuvable
      url: "/reference-network-path-not-found-error-during-vm-deployment.html"
    - title: Les ressources système sont insuffisantes pour terminer le service demandé
      url: "/reference-vm-provisioning-in-scvmm-fails-with-insufficient-system-resources-error.html"
    - title: La taille du partage SMB chute à 0 dans SCVMM
      url: "/reference-smb-share-size-dropping-to-0-in-scvmm.html"
    - title: L'opération de nouvelle analyse SCVMM n'a pas pu localiser ou communiquer
        avec SMI-S Provider
      url: "/reference-scvmm-rescan-operation-failed-to-locate-or-communicate-with-smi-s-provider.html"
  - title: Mentions légales
    url: "/reference-legal-notices.html"
