---
permalink: reference-cannot-add-a-storage-system-using-a-nondefault-http-or-https-port.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problèmes rencontrés avec le fournisseur NetApp SMI-S Provider. 
---
= Impossible d'ajouter un système de stockage à l'aide d'un port HTTP ou HTTPS non par défaut
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Numéro*
+
Vous ne pouvez pas ajouter un système de stockage exécutant HTTP ou HTTPS sur un port non défini par défaut.

* *Cause*
+
Par défaut, le fournisseur NetApp SMI-S utilise le port 80 pour communiquer avec les systèmes de stockage via HTTP et le port 443 pour communiquer via HTTPS.

* * Action corrective*
+
Utilisez la commande suivante pour ajouter un système de stockage utilisant un port autre que 80 pour le trafic HTTP ou le port 443 pour le trafic HTTPS :

+
`cimcli ci -n root/ontap ONTAP_FilerData hostName=_storage_sys_ip_address_ port=_non_default_port_ userName=_storage_sys_user_ password=_storage_sys_pwd_ comMechanism=HTTP -u _agent_user_ -p _agent_pwd_-llocalhost:5989 -s`

+
`-u`, `-p`, `-l`, et `-s` sont des paramètres facultatifs.





== Ajout d'un système de stockage utilisant le port 8000 pour le trafic HTTP

`cimcli ci -n root/ontap ONTAP_FilerData hostName=10.60.167.12 port=8000 userName=root password=netapp1! comMechanism=HTTP -u root -p netapp1! -l localhost:5989 -s --timeout 180`
