---
permalink: reference-entering-passwords-containing-special-characters.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problèmes rencontrés avec le fournisseur NetApp SMI-S Provider. 
---
= Problème de saisie des mots de passe contenant des caractères spéciaux
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Numéro*
+
Dans les systèmes d'exploitation de langue anglaise, à l'aide d'un mot de passe contenant des caractères spéciaux avec le `smis` La commande ne fonctionne pas dans un environnement Windows. Ce problème n'a pas été testé avec des systèmes d'exploitation non anglophones.

* *Cause*
+
Sous Windows, les caractères suivants, plus les espaces, sont considérés comme des caractères spéciaux et provoquent l'échec de la saisie du mot de passe si le mot de passe n'est pas inclus dans les guillemets :

+
, et ' < > ; | = {caret} "

* * Action corrective*
+
Si un mot de passe contient des espaces ou des caractères spéciaux, placez-le entre guillemets (" ") lorsque vous l'utilisez dans le `smis` commande. Notez que le caractère de citation (") est un caractère spécial et ne doit jamais être utilisé dans votre mot de passe.





== Émission de mots de passe avec caractères spéciaux

`smis add 1.2.3.4 Administrator "pass word"`

`smis add 1.2.3.4 Administrator "pass&word"`
