---
permalink: reference-cannot-connect-to-localhost-5988-error.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problèmes rencontrés avec le fournisseur NetApp SMI-S Provider. 
---
= Impossible de se connecter à localhost:5988
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Message*
+
`Cannot connect to localhost:5988. Connection failed. Trying to connect to localhost:5988`

* *Description*
+
Ce message s'affiche lorsque les connexions HTTPS sont désactivées ou que le port HTTPS n'est pas défini sur 5988, ou si le fournisseur a cessé de fonctionner et reste en état d'affichage.

* * Action corrective*
+
Vérifier que les valeurs de `enableHttpsConnection` et `httpsPort` sont correctes :

+
`cimconfig -g enableHttpConnection`

+
`cimconfig -g enableHttpsConnection`

+
`cimconfig -g httpPort`

+
`cimconfig -g httpsPort`

+
Si `enableHttpConnection` ou `enableHttpsConnection` n'est pas défini sur `true`, entrez les commandes suivantes :

+
`cimconfig -s enableHttpConnection -p`

+
`smis cimserver restart`

+
Si `httpPort` n'est pas défini sur 5988, saisissez les commandes suivantes :

+
`cimconfig -s httpPort=5988 -p`

+
`smis cimserver restart`

+
Si le fournisseur a cessé de fonctionner et reste à l'état d'affichage, ouvrez le Gestionnaire des tâches et mettez fin au processus, puis redémarrez le fournisseur.


