---
permalink: reference-smb-share-size-dropping-to-0-in-scvmm.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problèmes rencontrés avec le fournisseur NetApp SMI-S Provider. 
---
= La taille du partage SMB chute à 0 dans SCVMM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Numéro*
+
La taille de partage SMB 3.0, nouvelle ou existante, peut chuter à 0 dans System Center Virtual machine Manager (SCVMM).

* *Cause*
+
Si la réinitialisation des quotas prend beaucoup de temps dans ONTAP en raison d'E/S importantes, la taille du partage SMB 3.0 nouveau ou existant peut tomber à 0 dans SCVMM. Lorsque ce problème se produit, les nouvelles machines virtuelles ne peuvent pas être provisionnées sur des partages SMB 3.0 nouveaux ou existants.

* * Action corrective*
+
.. Désactivez les quotas.
.. Ajoutez une règle de quota par défaut de type « arborescence » sur chaque volume hébergeant des partages SMB.
.. Activez les quotas pour les volumes auxquels vous avez ajouté une règle de quota par défaut et redémarrez SMI-S Provider.



