---
permalink: reference-warning-26130.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problèmes rencontrés avec le fournisseur NetApp SMI-S Provider. 
---
= Avertissement 26130
:allow-uri-read: 
:icons: font
:imagesdir: ./media/




== Messagerie

`Warning (26130) Storage pool has been allocated to host group where none of hosts in host group has access to storage array.`



== Description

Cette erreur se produit lorsque vous allouez de la capacité de stockage et que vous accordez un accès à une baie aux hôtes d'un groupe d'hôtes. Avec cette mise en garde, il est impossible de placer des machines virtuelles sur les systèmes de stockage.



== Action corrective

. Sur chaque ordinateur hôte, ajoutez l'adresse IP de chaque système de stockage à l'application initiateur iSCSI.
. Si nécessaire, sur chaque système de stockage, créez un groupe initiateur unique lié au nom de nœud iSCSI approprié à partir de la machine hôte correspondante.
. Pour chaque ordinateur hôte connecté à Data ONTAP, ouvrez l'application MPIO et ajoutez l'ID matériel suivant :
+
** Si vous choisissez clustered Data ONTAP, entrez `*NETAPP LUN C-Mode*`.


. Redémarrez les ordinateurs hôtes.
. Supprimez le fournisseur.
. Définissez à nouveau le pool de stockage.

