---
permalink: reference-supported-operating-systems.html 
sidebar: sidebar 
keywords: installing, smi-s provider, verify, windows, host, operating systems 
summary: 'Avant d"installer SMI-S Provider, vous devez vérifier que l"hôte Windows exécute un système d"exploitation pris en charge.' 
---
= Versions de systèmes d'exploitation prises en charge
:allow-uri-read: 
:icons: font
:imagesdir: ./media/
:pp: &#43;&#43;


[role="lead"]
Nous vous recommandons d'installer le fournisseur SMI-S sur sa propre machine virtuelle Windows dédiée (VM). Cette machine virtuelle peut se trouver sur le même domaine pour permettre une gestion sécurisée et pratique.

Avant d'installer SMI-S Provider, vous devez vérifier que l'hôte Windows exécute un système d'exploitation pris en charge.

[cols="3*"]
|===
| Système d'exploitation | Versions prises en charge | Logiciel client requis 


 a| 
Répertoires de base
 a| 
* Microsoft Windows Server 2025
* Microsoft Windows Server 2022
* Microsoft Windows Server 2019
* Microsoft Windows Server 2016

 a| 
Les bibliothèques d'exécution Microsoft Visual C++ 2010 sont automatiquement installées lors de l'installation du fournisseur SMI-S. Pour éviter d'éventuels problèmes liés aux bibliothèques d'exécution, vous devez installer le package redistribuable Microsoft Visual C++ 2010 (x86) à partir de l'emplacement suivant : http://www.microsoft.com[]

|===


== Assurez-vous que la machine hôte du fournisseur réponde aux spécifications

Pour exécuter SMI-S Provider, la machine hôte du fournisseur doit respecter les spécifications suivantes :

* Le fournisseur ne peut pas être installé directement sur un nœud Hyper-V. Vous pouvez en revanche l'installer sur une machine virtuelle Hyper-V.
* Le gestionnaire de machines virtuelles System Center (SCVMM) ne doit pas être exécuté sur la machine hôte du fournisseur.
* La machine hôte du fournisseur ne doit pas exécuter d'autres programmes consommant beaucoup de mémoire.
* La machine hôte du fournisseur ne doit pas exécuter de fournisseurs SMI-S provenant d'un autre fournisseur.

