---
permalink: task-generate-a-self-signed-certificate-for-the-cim-server-windows.html 
sidebar: sidebar 
keywords: ssl authentication, enable, cim server, installation, self-signed certificate 
summary: 'Par défaut, l"authentification SSL est activée pour le serveur CIM. Lors de l"installation du SMI-S Provider, un certificat auto-signé pour le serveur CIM est installé dans le répertoire pegasus. Vous pouvez générer votre propre certificat auto-signé et l"utiliser plutôt que le certificat par défaut.' 
---
= Générez un certificat auto-signé pour le serveur CIM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Par défaut, l'authentification SSL est activée pour le serveur CIM. Lors de l'installation du SMI-S Provider, un certificat auto-signé pour le serveur CIM est installé dans le `pegasus` répertoire. Vous pouvez générer votre propre certificat auto-signé et l'utiliser plutôt que le certificat par défaut.

.Avant de commencer
* Vous devez déjà vous connecter en tant qu'administrateur.
* Vous devez avoir déjà accédé à SMI-S Provider.


.Étapes
. Téléchargez le `openssl.cnf` fichier à partir de l'emplacement suivant : link:http://web.mit.edu/crypto/openssl.cnf["http://web.mit.edu/crypto/openssl.cnf"^]
. Déplacer le `openssl.cnf` fichier dans le répertoire bin :
+
`*%PEGASUS_HOME%\bin\openssl.cnf*`

. Réglez le `OPENSSL_CONF` variable environnementale à l'emplacement du `openssl.cnf` fichier :
+
`*C:\ >set OPENSSL_CONF=%PEGASUS_HOME%\bin\openssl.cnf*`

+
Ceci définit uniquement la variable d'environnement pour la durée de la session d'invite de commande en cours. Si vous souhaitez définir de façon permanente la variable d'environnement, vous pouvez utiliser l'une des options suivantes :

+
** Naviguez jusqu'à *Propriétés > variables d'environnement* et mettez à jour la variable sous *système*.
** Utilisez invite de commande pour définir de façon permanente la variable :
+
`*setx OPENSSL_CONF “%PEGASUS_HOME%\bin\openssl.cnf*`.

+
La variable est définie lorsque vous ouvrez une nouvelle session d'invite de commande.



. Accédez au `%PEGASUS_HOME%\bin` répertoire :
+
`*C:\cd %pegasus_home%\bin*`

. Générer une clé privée :
+
`*openssl genrsa -out cimom.key 2048*`

. Générer une demande de certificat :
+
`*openssl req -new -key cimom.key -out cimom.csr*`

. Entrez vos informations pour la demande de certificat lorsque vous y êtes invité.
. Générer le certificat auto-signé :
+
`*openssl x509 -in cimom.csr -out cimom.cert -req -signkey cimom.key -days 1095*`

+
Vous pouvez indiquer un nombre de jours différent pour lequel le certificat est valide.

. Copiez le `cimom.key` et `cimom.cert` fichiers vers le `pegasus` Répertoire (Windows : `C:\Program Files (x86)\NetApp\smis\pegasus`).




== Résultat

La plage de dates du certificat commence à la date actuelle et s'exécute pendant le nombre de jours spécifié.
