---
permalink: task-generate-a-self-signed-certificate-for-the-cim-server-windows.html 
sidebar: sidebar 
keywords: ssl authentication, enable, cim server, installation, self-signed certificate 
summary: 'Par défaut, l"authentification SSL est activée pour le serveur CIM. Lors de l"installation du SMI-S Provider, un certificat auto-signé pour le serveur CIM est installé dans le répertoire pegasus. Vous pouvez générer votre propre certificat auto-signé et l"utiliser plutôt que le certificat par défaut.' 
---
= Générez un certificat auto-signé pour le serveur CIM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
L'authentification SSL est activée par défaut pour le serveur CIM. Lors de l'installation du fournisseur SMI-S, un certificat auto-signé pour le serveur CIM est installé dans le `pegasus` annuaire. Vous devez générer votre propre certificat auto-signé au lieu d'utiliser le certificat par défaut.


CAUTION: Lorsque vous installez le fournisseur SMI-S, le certificat auto-signé par défaut installé est obsolète. En conséquence, la connexion SSL au fournisseur SMI-S échoue à partir de *Ajouter des périphériques de stockage* dans System Center Virtual Machine Manager (SCVMM). Vous devez générer un certificat auto-signé pour le serveur CIM et redémarrer ensuite le service SMI-S Provider. Pour plus d'informations, veuillez consulter link:https://kb.netapp.com/data-mgmt/SMI-S/SMI-S_Issues/CSMIS-3["Article de la base de connaissances NetApp : « CSMIS-3 : le certificat cimom.cert du NetApp SMI-S Provider 5.2.7 a expiré au moment de l’installation. »"^]

.Avant de commencer
* Vous devez déjà vous connecter en tant qu'administrateur.
* Vous devez avoir déjà accédé à SMI-S Provider.
* Vous devez avoir téléchargé et installé OpenSSL sur votre système Windows.


.Étapes
. Téléchargez le `openssl.cnf` fichier à partir de l'emplacement suivant : link:http://web.mit.edu/crypto/openssl.cnf["http://web.mit.edu/crypto/openssl.cnf"^]
. Déplacer le `openssl.cnf` fichier dans le répertoire bin :
+
`*%PEGASUS_HOME%\bin\openssl.cnf*`

. Réglez le `OPENSSL_CONF` variable environnementale à l'emplacement du `openssl.cnf` fichier :
+
`*C:\ >set OPENSSL_CONF=%PEGASUS_HOME%\bin\openssl.cnf*`

+
Ceci définit uniquement la variable d'environnement pour la durée de la session d'invite de commande en cours. Si vous souhaitez définir de façon permanente la variable d'environnement, vous pouvez utiliser l'une des options suivantes :

+
** Naviguez jusqu'à *Propriétés > variables d'environnement* et mettez à jour la variable sous *système*.
** Utilisez invite de commande pour définir de façon permanente la variable :
+
`*setx OPENSSL_CONF “%PEGASUS_HOME%\bin\openssl.cnf*`.

+
La variable est définie lorsque vous ouvrez une nouvelle session d'invite de commande.



. Accédez au `%PEGASUS_HOME%\bin` répertoire :
+
`*C:\cd %pegasus_home%\bin*`

. Générer une clé privée :
+
`*openssl genrsa -out cimom.key 2048*`

. Générer une demande de certificat :
+
`*openssl req -new -key cimom.key -out cimom.csr*`

. Entrez vos informations pour la demande de certificat lorsque vous y êtes invité.
. Générer le certificat auto-signé :
+
`*openssl x509 -in cimom.csr -out cimom.cert -req -signkey cimom.key -days 1095*`

+
Vous pouvez indiquer un nombre de jours différent pour lequel le certificat est valide.

. Copiez le `cimom.key` et `cimom.cert` fichiers vers le `pegasus` Répertoire (Windows : `C:\Program Files (x86)\NetApp\smis\pegasus`).
. Redémarrez le service du fournisseur SMI-S :
+
`smis cimserver restart`





[[result]]
== Résultat

La plage de dates du certificat commence à la date actuelle et s'exécute pendant le nombre de jours spécifié.
